[package]
name = "sensehat-screen"
description = "A Rust library for using the 8x8-LED RGB565 screen on the Raspberry SenseHat device."
version = "0.1.4"
authors = ["Joaquin Rosales <globojorro@gmail.com>"]
keywords = ["sensehat", "screen", "8x8", "raspberry-pi", "framebuffer"]
categories = ["embedded", "rendering", "visualization", "encoding"]
homepage = "https://github.com/saibatizoku/sensehat-screen-rs"
repository = "https://github.com/saibatizoku/sensehat-screen-rs"
readme = "README.md"
license = "MIT"

[dependencies]
framebuffer = { version = "0.1", optional = true }
font8x8 = { version = "0.1", optional = true }
glob = "0.2"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[features]
default = ["linux-framebuffer", "rgb565", "fonts", "serde-support", "little-endian"]
big-endian = []
little-endian = []
rgb565 = []
linux-framebuffer = ["framebuffer"]
fonts = ["font8x8"]
serde-support = ["serde", "serde_derive"]

[profile.release]
#lto = true
