[package]
name = "sensehat-screen"
description = "A Rust library for using the 8x8-LED RGB565 screen on the Raspberry SenseHat device."
version = "0.1.0"
authors = ["Joaquin Rosales <globojorro@gmail.com>"]
license = "MIT"

[dependencies]
framebuffer = "0.1"
font8x8 = { version = "0.1", optional = true }
glob = "0.2"

[features]
default = ["fonts"]
fonts = ["font8x8"]
